name: Deploy on VPN

on:
  push:
    branches:
       - main

jobs:
  deploy:
    runs-on: ubunto-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-agent bash -c "ssh-add - <<< '${SSH_PRIVATE_KEY}' && \
          ssh -o StrictHostKeyChecking=no gi.carnaval@hotmail.com 'cd /var/www/my-server && git pull && npm install && pm2 restart all"